[profile.default]
# compatible with truffle
src = "contracts"
out = 'out'
libs = ["node_modules"]
remappings = [
    '@chainlink/=node_modules/@chainlink/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@eth-optimism/=node_modules/@eth-optimism/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'erc721psi/=node_modules/erc721psi/',
    'operator-filter-registry/=node_modules/operator-filter-registry/',
    'solidity-bits/=node_modules/solidity-bits/',
    'truffle/=node_modules/truffle/',
    'forge-std/=lib/forge-std/src/',
    'ds-test/=lib/forge-std/lib/ds-test/src/'
]
gas_reports = ["ShellzOrbV2"]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config